-- MySQL Script generated by MySQL Workbench
-- Fri Jan 11 18:33:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bet_group
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bet_group
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bet_group` DEFAULT CHARACTER SET utf8 ;
USE `bet_group` ;

-- -----------------------------------------------------
-- Table `bet_group`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bet_group`.`user` ;

CREATE TABLE IF NOT EXISTS `bet_group`.`user` (
  `id` INT NOT NULL COMMENT '	',
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  `deletedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bet_group`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bet_group`.`group` ;

CREATE TABLE IF NOT EXISTS `bet_group`.`group` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  `deletedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bet_group`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bet_group`.`game` ;

CREATE TABLE IF NOT EXISTS `bet_group`.`game` (
  `id` INT NOT NULL,
  `startDate` DATETIME NULL,
  `limitDate` DATETIME NULL,
  `endDate` DATETIME NULL,
  `status` INT NULL,
  `updatedAt` DATETIME NULL,
  `deletedAt` DATETIME NULL,
  `betPrice` DOUBLE NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_game_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_game_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `bet_group`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bet_group`.`bet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bet_group`.`bet` ;

CREATE TABLE IF NOT EXISTS `bet_group`.`bet` (
  `id` INT NOT NULL,
  `status` INT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  `deletedAt` DATETIME NULL,
  `user_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bet_user1_idx` (`user_id` ASC),
  INDEX `fk_bet_game1_idx` (`game_id` ASC),
  CONSTRAINT `fk_bet_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bet_group`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bet_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `bet_group`.`game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bet_group`.`bet_numbers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bet_group`.`bet_numbers` ;

CREATE TABLE IF NOT EXISTS `bet_group`.`bet_numbers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `bet_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bet_numbers_bet1_idx` (`bet_id` ASC),
  CONSTRAINT `fk_bet_numbers_bet1`
    FOREIGN KEY (`bet_id`)
    REFERENCES `bet_group`.`bet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bet_group`.`result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bet_group`.`result` ;

CREATE TABLE IF NOT EXISTS `bet_group`.`result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`id`, `game_id`),
  INDEX `fk_result_game1_idx` (`game_id` ASC),
  CONSTRAINT `fk_result_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `bet_group`.`game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bet_group`.`lottery_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bet_group`.`lottery_result` ;

CREATE TABLE IF NOT EXISTS `bet_group`.`lottery_result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL,
  `type` INT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bet_group`.`lotery_result_number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bet_group`.`lotery_result_number` ;

CREATE TABLE IF NOT EXISTS `bet_group`.`lotery_result_number` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL,
  `lottery_result_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lotery_result_number_lottery_result1_idx` (`lottery_result_id` ASC),
  CONSTRAINT `fk_lotery_result_number_lottery_result1`
    FOREIGN KEY (`lottery_result_id`)
    REFERENCES `bet_group`.`lottery_result` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bet_group`.`user_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bet_group`.`user_group` ;

CREATE TABLE IF NOT EXISTS `bet_group`.`user_group` (
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`user_id`, `group_id`),
  INDEX `fk_user_has_group_group1_idx` (`group_id` ASC),
  INDEX `fk_user_has_group_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_group_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `bet_group`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `bet_group`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bet_group`.`lottery_result_game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bet_group`.`lottery_result_game` ;

CREATE TABLE IF NOT EXISTS `bet_group`.`lottery_result_game` (
  `lottery_result_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`lottery_result_id`, `game_id`),
  INDEX `fk_lottery_result_has_game_game1_idx` (`game_id` ASC),
  INDEX `fk_lottery_result_has_game_lottery_result1_idx` (`lottery_result_id` ASC),
  CONSTRAINT `fk_lottery_result_has_game_lottery_result1`
    FOREIGN KEY (`lottery_result_id`)
    REFERENCES `bet_group`.`lottery_result` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lottery_result_has_game_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `bet_group`.`game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
